/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package MyNewGradleProj;
import picocli.CommandLine;
import picocli.CommandLine.Command;

import java.util.concurrent.Callable;

@CommandLine.Command(name="app",resourceBundle = "app_messages",subcommands = {CommandLine.HelpCommand.class})
public class App implements Callable {
    public String getGreeting() {
        return "Hello world.";
    }
    @Command(name="mul", resourceBundle = "app_messages")
    public static int multiply(@CommandLine.Parameters(paramLabel = "factors", arity = "1..*") int[] factors) {
        int prod = 1;
        for (int f: factors) {
            prod *= f;
        }
        System.out.println(prod);
        return prod;
    }
    @Command(name="add")
    public static int add(@CommandLine.Parameters(paramLabel = "summands", arity = "1..*") int[] summands) {
        int sum = 0;
        for (int s: summands) {
            sum += s;
        }
        System.out.println(sum);
        return sum;
    }
    @Command(name="avg")
    public static double avg(@CommandLine.Parameters(paramLabel = "terms", arity = "1..*") double[] terms) {
        double sum = 0;
        int count = 0;
        for (double s: terms) {
            sum += s;
            count++;
        }
        double av = sum/count;
        System.out.println(av);
        return av;
    }


    public static void main(String[] args) {
//        System.out.println(new App().getGreeting());
        int exitCode = new CommandLine(new App()).execute(args);

    }

    @Override
    public Object call() throws Exception {
        return null;
    }
}
